name: CDK Scan Pipeline Demo
run-name: ${{ github.actor }} has triggered Scan Action 🚀
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

env:
  NIRMATA_TOKEN: ${{ secrets.NIRMATA_TOKEN }}
  NIRMATA_URL: ${{ secrets.NIRMATA_URL }}

jobs:
  NCTL-Scan-Repository:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out main repository code
        uses: actions/checkout@v4

      - name: NCTL-scan-installer
        uses: supplypike/setup-bin@v4
        with:
          uri: 'https://nirmata-downloads.s3.us-east-2.amazonaws.com/nctl/nctl_4.2.2-rc.1/nctl_4.2.2-rc.1_linux_386.zip'
          name: 'nctl'
          version: '4.2.2-rc.1'

      - name: Check nctl version
        run: |
          nctl version

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm install

      - name: Install Python dependencies and CDK
        run: |
          python -m pip install --upgrade pip
          cd sample-cdk
          pip install -r requirements.txt
          npm install -g aws-cdk

      - name: CDK Synth
        run: |
          cd sample-cdk
          cdk synth --json

      - name: nctl login
        run: nctl login --url $NIRMATA_URL --userid anusha.hegde@nirmata.com --token $NIRMATA_TOKEN
        
        
      - name: NCTL Scan Repository for CDK
        run: |
          nctl scan json sample-cdk/cdk.out/MyEcsStack.template.json --policies policies/
  
      - run: echo "🍏 This job's status is ${{ job.status }}."